"""Added laguage to the posts

Revision ID: 14ba94822523
Revises: 14fb662246eb
Create Date: 2020-05-01 20:27:29.507742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14ba94822523"
down_revision = "14fb662246eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("language", sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "language")
    # ### end Alembic commands ###
