"""Added followers table

Revision ID: 14fb662246eb
Revises: d90aea1c5a1c
Create Date: 2020-05-01 15:06:47.945927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14fb662246eb"
down_revision = "d90aea1c5a1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["followed_id"], ["user.id"],),
        sa.ForeignKeyConstraint(["follower_id"], ["user.id"],),
    )
    op.create_index(
        op.f("ix_followers_followed_id"), "followers", ["followed_id"], unique=False
    )
    op.create_index(
        op.f("ix_followers_follower_id"), "followers", ["follower_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_followers_follower_id"), table_name="followers")
    op.drop_index(op.f("ix_followers_followed_id"), table_name="followers")
    op.drop_table("followers")
    # ### end Alembic commands ###
